apiVersion: v1
kind: Service
metadata:
  name: minio-client
spec:
  selector:
    app: minio-client
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-client
  labels:
    app: minio-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-client
  template:
    metadata:
      labels:
        app: minio-client
    spec:
      containers:
      - name: minio-client
        image: davidpauleg/minio:latest
        ports:
        - containerPort: 5000
        env:
        - name: ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: minio-server
              key: access_key
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: minio-server
              key: secret_key
