apiVersion: v1
kind: Service
metadata:
  name: minio-web
spec:
  selector:
    app: minio-web
  ports:
    - protocol: TCP
      port: 9000
      targetPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: minio-api
spec:
  selector:
    app: minio-api
  ports:
    - protocol: TCP
      port: 9001
      targetPort: 9001
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio-server
  labels:
    app: minio-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio-server
  template:
    metadata:
      labels:
        app: minio-server
    spec:
      containers:
      - name: minio-server
        image: minio/minio
        command: ["minio"]
        args: ["server", "/data"]
        ports:
        - containerPort: 9000
        - containerPort: 9001